package com.finzly.ems.employeepu;

// Generated 27 May, 2020 11:20:36 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Employee generated by hbm2java
 */
@Entity
@Table(name = "employee", catalog = "ems")
public class Employee implements java.io.Serializable {

	private String employeeid;
	private String name;
	private String native_;
	private Integer yoe;
	private Date joiningdate;
	private Date dateofbirth;

	public Employee() {
	}

	public Employee(String employeeid) {
		this.employeeid = employeeid;
	}

	public Employee(String employeeid, String name, String native_,
			Integer yoe, Date joiningdate, Date dateofbirth) {
		this.employeeid = employeeid;
		this.name = name;
		this.native_ = native_;
		this.yoe = yoe;
		this.joiningdate = joiningdate;
		this.dateofbirth = dateofbirth;
	}

	@Id
	@Column(name = "employeeid", unique = true, nullable = false, length = 50)
	public String getEmployeeid() {
		return this.employeeid;
	}

	public void setEmployeeid(String employeeid) {
		this.employeeid = employeeid;
	}

	@Column(name = "name", length = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "native", length = 50)
	public String getNative_() {
		return this.native_;
	}

	public void setNative_(String native_) {
		this.native_ = native_;
	}

	@Column(name = "yoe")
	public Integer getYoe() {
		return this.yoe;
	}

	public void setYoe(Integer yoe) {
		this.yoe = yoe;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "joiningdate", length = 10)
	public Date getJoiningdate() {
		return this.joiningdate;
	}

	public void setJoiningdate(Date joiningdate) {
		this.joiningdate = joiningdate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dateofbirth", length = 10)
	public Date getDateofbirth() {
		return this.dateofbirth;
	}

	public void setDateofbirth(Date dateofbirth) {
		this.dateofbirth = dateofbirth;
	}

}
